### ISSUE TITLE
倒入后会清空safari的reading list

### ISSUE THREAD

**Issue by guoyida** [binss/import_bookmarks_from_chrome_to_safari#1]
然而并不想清空

**Comment by binss** [comment]
已尝试修复，麻烦再试一下

**Comment by guoyida** [comment]
之前测试直接用的app版本的，作者好像只改了py脚本，直接运行py脚本报错
Traceback (most recent call last):
  File "/Volumes/Transcend/Downloads/import_bookmarks_from_chrome_to_safari-master/import_bookmark.py", line 110, in <module>
    main()
  File "/Volumes/Transcend/Downloads/import_bookmarks_from_chrome_to_safari-master/import_bookmark.py", line 98, in main
    bookmark_manager.load_from_chrome(chrome_info)
  File "/Volumes/Transcend/Downloads/import_bookmarks_from_chrome_to_safari-master/import_bookmark.py", line 54, in load_from_chrome
    new_bookmarks, new_number = load_bookmark(raw_list)
  File "/Volumes/Transcend/Downloads/import_bookmarks_from_chrome_to_safari-master/import_bookmark.py", line 43, in load_bookmark
    children, children_num = load_bookmark(raw_dict["children"])
  File "/Volumes/Transcend/Downloads/import_bookmarks_from_chrome_to_safari-master/import_bookmark.py", line 48, in load_bookmark
    bookmark = {"name": raw_dict["name"], "url": raw_dict["url"], "time": parse_chrome_time(raw_dict["date_added"])}
KeyError: 'url'

python版本为Python 2.7.9 :: Anaconda 2.1.0 (x86_64)

**Comment by binss** [comment]
APP版实际上了用了applescript来做，调用的是Safari自己的功能。这个无法控制。我自己都是用Python版。

我测试自己的书签没有这种情况，根据错误来看，应该是这个书签没有url？建议打印raw_dict看看内容

**Comment by guoyida** [comment]
print出来了 raw_dict，发现导入过程一直导入了“下文献”那一条，后面的other bookmarks都没有，不知道这个other bookmarks是不是有什么特殊的结构

<img width="498" alt="screen shot 2016-05-10 at 16 33 33" src="https://cloud.githubusercontent.com/assets/5548602/15152391/ffdda372-16cc-11e6-87db-290d340b3383.png">

**Comment by binss** [comment]
other bookmarks文件夹和常规的书签不在同一个结构中，所以没有被解析导入。在新的版本中应该可以导入了。但奇怪的是在我的机器上即使没被解析导入，也不会抛出错误，如果你在新版本中还是有这个问题，麻烦把print出来的内容粘一下
